#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusViewer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Focus")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBrief(Brief instance);
    partial void UpdateBrief(Brief instance);
    partial void DeleteBrief(Brief instance);
    partial void InsertCodeUpdate(CodeUpdate instance);
    partial void UpdateCodeUpdate(CodeUpdate instance);
    partial void DeleteCodeUpdate(CodeUpdate instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::FocusViewer.Properties.Settings.Default.FocusConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Brief> Briefs
		{
			get
			{
				return this.GetTable<Brief>();
			}
		}
		
		public System.Data.Linq.Table<Symbol> Symbols
		{
			get
			{
				return this.GetTable<Symbol>();
			}
		}
		
		public System.Data.Linq.Table<CodeUpdate> CodeUpdates
		{
			get
			{
				return this.GetTable<CodeUpdate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Briefs")]
	public partial class Brief : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BriefID;
		
		private System.Data.Linq.Binary _BriefBytes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBriefIDChanging(int value);
    partial void OnBriefIDChanged();
    partial void OnBriefBytesChanging(System.Data.Linq.Binary value);
    partial void OnBriefBytesChanged();
    #endregion
		
		public Brief()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BriefID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BriefID
		{
			get
			{
				return this._BriefID;
			}
			set
			{
				if ((this._BriefID != value))
				{
					this.OnBriefIDChanging(value);
					this.SendPropertyChanging();
					this._BriefID = value;
					this.SendPropertyChanged("BriefID");
					this.OnBriefIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BriefBytes", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BriefBytes
		{
			get
			{
				return this._BriefBytes;
			}
			set
			{
				if ((this._BriefBytes != value))
				{
					this.OnBriefBytesChanging(value);
					this.SendPropertyChanging();
					this._BriefBytes = value;
					this.SendPropertyChanged("BriefBytes");
					this.OnBriefBytesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Symbols")]
	public partial class Symbol
	{
		
		private short _SymbolID;
		
		private string _FullName;
		
		private string _Type;
		
		private string _Market;
		
		private string _Name;
		
		public Symbol()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolID", DbType="SmallInt NOT NULL")]
		public short SymbolID
		{
			get
			{
				return this._SymbolID;
			}
			set
			{
				if ((this._SymbolID != value))
				{
					this._SymbolID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NChar(32)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NChar(10)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Market", DbType="NChar(10)")]
		public string Market
		{
			get
			{
				return this._Market;
			}
			set
			{
				if ((this._Market != value))
				{
					this._Market = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(10)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CodeUpdates")]
	public partial class CodeUpdate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ide;
		
		private System.Nullable<int> _brfVersion;
		
		private System.Nullable<double> _TotalTime;
		
		private System.Nullable<System.DateTime> _Added;
		
		private System.Nullable<int> _PROG;
		
		private System.Nullable<int> _Signals;
		
		private System.Data.Linq.Binary _code;
		
		private System.Nullable<double> _score;
		
		private System.Nullable<int> _TwkBitFlipCt;
		
		private System.Nullable<double> _unTestedScore;
		
		private System.Nullable<double> _midEntryPointScore;
		
		private System.Nullable<double> _DisplayScore;
		
		private System.Nullable<double> _DisplayUnTestedScore;
		
		private System.Nullable<int> _RunCt;
		
		private System.Nullable<int> _WinCt;
		
		private System.Nullable<int> _FailedReRunCt;
		
		private System.Nullable<int> _CutOffCt;
		
		private System.Nullable<int> _NoChangeDetCt;
		
		private System.Nullable<int> _DegradeFloorCt;
		
		private System.Nullable<int> _KeepWithSmallDegCt;
		
		private System.Nullable<int> _FailedMinTrdCtRuleCt;
		
		private System.Nullable<int> _Cutoffs0;
		
		private System.Nullable<int> _Cutoffs1;
		
		private System.Nullable<int> _Cutoffs2;
		
		private System.Nullable<int> _Cutoffs3;
		
		private System.Nullable<int> _Cutoffs4;
		
		private System.Nullable<int> _Cutoffs5;
		
		private System.Nullable<int> _Cutoffs6;
		
		private System.Nullable<int> _Cutoffs7;
		
		private System.Nullable<int> _Cutoffs8;
		
		private System.Nullable<int> _Cutoffs9;
		
		private System.Nullable<int> _Cutoffs10;
		
		private System.Nullable<double> _TrdCtAvg;
		
		private System.Nullable<double> _Trd0Ct;
		
		private System.Nullable<double> _Trd1Ct;
		
		private System.Nullable<double> _Trd2Ct;
		
		private System.Nullable<double> _Trd3Ct;
		
		private System.Nullable<double> _Trd4Ct;
		
		private System.Nullable<double> _Trd5Ct;
		
		private System.Nullable<double> _Trd6Ct;
		
		private System.Nullable<double> _Trd7Ct;
		
		private System.Nullable<double> _MyScore0;
		
		private System.Nullable<double> _MyScore1;
		
		private System.Nullable<double> _MyScore2;
		
		private System.Nullable<double> _MyScore3;
		
		private System.Nullable<double> _MyScore4;
		
		private System.Nullable<double> _MyScore5;
		
		private System.Nullable<double> _MyScore6;
		
		private System.Nullable<double> _MyScore7;
		
		private System.Nullable<double> _MyScore8;
		
		private System.Nullable<double> _MyScore9;
		
		private System.Nullable<double> _MyScore10;
		
		private System.Nullable<double> _MyScore11;
		
		private System.Nullable<double> _MyScore12;
		
		private System.Nullable<double> _MyScore13;
		
		private System.Nullable<double> _MyScore14;
		
		private System.Nullable<double> _MyScore15;
		
		private System.Nullable<double> _MyScore16;
		
		private System.Nullable<double> _MyScore17;
		
		private System.Nullable<double> _MyScore18;
		
		private System.Nullable<double> _MyScore19;
		
		private System.Nullable<double> _MyScore20;
		
		private System.Nullable<double> _MyScore21;
		
		private System.Nullable<double> _MyScore22;
		
		private System.Nullable<double> _MyScore23;
		
		private System.Nullable<double> _MyScore24;
		
		private System.Nullable<double> _MyScore25;
		
		private System.Nullable<double> _MyScore26;
		
		private System.Nullable<double> _MyScore27;
		
		private System.Nullable<double> _MyScore28;
		
		private System.Nullable<double> _MyScore29;
		
		private System.Nullable<double> _MyScore30;
		
		private System.Nullable<double> _MyScore31;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnideChanging(int value);
    partial void OnideChanged();
    partial void OnbrfVersionChanging(System.Nullable<int> value);
    partial void OnbrfVersionChanged();
    partial void OnTotalTimeChanging(System.Nullable<double> value);
    partial void OnTotalTimeChanged();
    partial void OnAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnAddedChanged();
    partial void OnPROGChanging(System.Nullable<int> value);
    partial void OnPROGChanged();
    partial void OnSignalsChanging(System.Nullable<int> value);
    partial void OnSignalsChanged();
    partial void OncodeChanging(System.Data.Linq.Binary value);
    partial void OncodeChanged();
    partial void OnscoreChanging(System.Nullable<double> value);
    partial void OnscoreChanged();
    partial void OnTwkBitFlipCtChanging(System.Nullable<int> value);
    partial void OnTwkBitFlipCtChanged();
    partial void OnunTestedScoreChanging(System.Nullable<double> value);
    partial void OnunTestedScoreChanged();
    partial void OnmidEntryPointScoreChanging(System.Nullable<double> value);
    partial void OnmidEntryPointScoreChanged();
    partial void OnDisplayScoreChanging(System.Nullable<double> value);
    partial void OnDisplayScoreChanged();
    partial void OnDisplayUnTestedScoreChanging(System.Nullable<double> value);
    partial void OnDisplayUnTestedScoreChanged();
    partial void OnRunCtChanging(System.Nullable<int> value);
    partial void OnRunCtChanged();
    partial void OnWinCtChanging(System.Nullable<int> value);
    partial void OnWinCtChanged();
    partial void OnFailedReRunCtChanging(System.Nullable<int> value);
    partial void OnFailedReRunCtChanged();
    partial void OnCutOffCtChanging(System.Nullable<int> value);
    partial void OnCutOffCtChanged();
    partial void OnNoChangeDetCtChanging(System.Nullable<int> value);
    partial void OnNoChangeDetCtChanged();
    partial void OnDegradeFloorCtChanging(System.Nullable<int> value);
    partial void OnDegradeFloorCtChanged();
    partial void OnKeepWithSmallDegCtChanging(System.Nullable<int> value);
    partial void OnKeepWithSmallDegCtChanged();
    partial void OnFailedMinTrdCtRuleCtChanging(System.Nullable<int> value);
    partial void OnFailedMinTrdCtRuleCtChanged();
    partial void OnCutoffs0Changing(System.Nullable<int> value);
    partial void OnCutoffs0Changed();
    partial void OnCutoffs1Changing(System.Nullable<int> value);
    partial void OnCutoffs1Changed();
    partial void OnCutoffs2Changing(System.Nullable<int> value);
    partial void OnCutoffs2Changed();
    partial void OnCutoffs3Changing(System.Nullable<int> value);
    partial void OnCutoffs3Changed();
    partial void OnCutoffs4Changing(System.Nullable<int> value);
    partial void OnCutoffs4Changed();
    partial void OnCutoffs5Changing(System.Nullable<int> value);
    partial void OnCutoffs5Changed();
    partial void OnCutoffs6Changing(System.Nullable<int> value);
    partial void OnCutoffs6Changed();
    partial void OnCutoffs7Changing(System.Nullable<int> value);
    partial void OnCutoffs7Changed();
    partial void OnCutoffs8Changing(System.Nullable<int> value);
    partial void OnCutoffs8Changed();
    partial void OnCutoffs9Changing(System.Nullable<int> value);
    partial void OnCutoffs9Changed();
    partial void OnCutoffs10Changing(System.Nullable<int> value);
    partial void OnCutoffs10Changed();
    partial void OnTrdCtAvgChanging(System.Nullable<double> value);
    partial void OnTrdCtAvgChanged();
    partial void OnTrd0CtChanging(System.Nullable<double> value);
    partial void OnTrd0CtChanged();
    partial void OnTrd1CtChanging(System.Nullable<double> value);
    partial void OnTrd1CtChanged();
    partial void OnTrd2CtChanging(System.Nullable<double> value);
    partial void OnTrd2CtChanged();
    partial void OnTrd3CtChanging(System.Nullable<double> value);
    partial void OnTrd3CtChanged();
    partial void OnTrd4CtChanging(System.Nullable<double> value);
    partial void OnTrd4CtChanged();
    partial void OnTrd5CtChanging(System.Nullable<double> value);
    partial void OnTrd5CtChanged();
    partial void OnTrd6CtChanging(System.Nullable<double> value);
    partial void OnTrd6CtChanged();
    partial void OnTrd7CtChanging(System.Nullable<double> value);
    partial void OnTrd7CtChanged();
    partial void OnMyScore0Changing(System.Nullable<double> value);
    partial void OnMyScore0Changed();
    partial void OnMyScore1Changing(System.Nullable<double> value);
    partial void OnMyScore1Changed();
    partial void OnMyScore2Changing(System.Nullable<double> value);
    partial void OnMyScore2Changed();
    partial void OnMyScore3Changing(System.Nullable<double> value);
    partial void OnMyScore3Changed();
    partial void OnMyScore4Changing(System.Nullable<double> value);
    partial void OnMyScore4Changed();
    partial void OnMyScore5Changing(System.Nullable<double> value);
    partial void OnMyScore5Changed();
    partial void OnMyScore6Changing(System.Nullable<double> value);
    partial void OnMyScore6Changed();
    partial void OnMyScore7Changing(System.Nullable<double> value);
    partial void OnMyScore7Changed();
    partial void OnMyScore8Changing(System.Nullable<double> value);
    partial void OnMyScore8Changed();
    partial void OnMyScore9Changing(System.Nullable<double> value);
    partial void OnMyScore9Changed();
    partial void OnMyScore10Changing(System.Nullable<double> value);
    partial void OnMyScore10Changed();
    partial void OnMyScore11Changing(System.Nullable<double> value);
    partial void OnMyScore11Changed();
    partial void OnMyScore12Changing(System.Nullable<double> value);
    partial void OnMyScore12Changed();
    partial void OnMyScore13Changing(System.Nullable<double> value);
    partial void OnMyScore13Changed();
    partial void OnMyScore14Changing(System.Nullable<double> value);
    partial void OnMyScore14Changed();
    partial void OnMyScore15Changing(System.Nullable<double> value);
    partial void OnMyScore15Changed();
    partial void OnMyScore16Changing(System.Nullable<double> value);
    partial void OnMyScore16Changed();
    partial void OnMyScore17Changing(System.Nullable<double> value);
    partial void OnMyScore17Changed();
    partial void OnMyScore18Changing(System.Nullable<double> value);
    partial void OnMyScore18Changed();
    partial void OnMyScore19Changing(System.Nullable<double> value);
    partial void OnMyScore19Changed();
    partial void OnMyScore20Changing(System.Nullable<double> value);
    partial void OnMyScore20Changed();
    partial void OnMyScore21Changing(System.Nullable<double> value);
    partial void OnMyScore21Changed();
    partial void OnMyScore22Changing(System.Nullable<double> value);
    partial void OnMyScore22Changed();
    partial void OnMyScore23Changing(System.Nullable<double> value);
    partial void OnMyScore23Changed();
    partial void OnMyScore24Changing(System.Nullable<double> value);
    partial void OnMyScore24Changed();
    partial void OnMyScore25Changing(System.Nullable<double> value);
    partial void OnMyScore25Changed();
    partial void OnMyScore26Changing(System.Nullable<double> value);
    partial void OnMyScore26Changed();
    partial void OnMyScore27Changing(System.Nullable<double> value);
    partial void OnMyScore27Changed();
    partial void OnMyScore28Changing(System.Nullable<double> value);
    partial void OnMyScore28Changed();
    partial void OnMyScore29Changing(System.Nullable<double> value);
    partial void OnMyScore29Changed();
    partial void OnMyScore30Changing(System.Nullable<double> value);
    partial void OnMyScore30Changed();
    partial void OnMyScore31Changing(System.Nullable<double> value);
    partial void OnMyScore31Changed();
    #endregion
		
		public CodeUpdate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ide", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ide
		{
			get
			{
				return this._ide;
			}
			set
			{
				if ((this._ide != value))
				{
					this.OnideChanging(value);
					this.SendPropertyChanging();
					this._ide = value;
					this.SendPropertyChanged("ide");
					this.OnideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brfVersion", DbType="Int")]
		public System.Nullable<int> brfVersion
		{
			get
			{
				return this._brfVersion;
			}
			set
			{
				if ((this._brfVersion != value))
				{
					this.OnbrfVersionChanging(value);
					this.SendPropertyChanging();
					this._brfVersion = value;
					this.SendPropertyChanged("brfVersion");
					this.OnbrfVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTime", DbType="Float")]
		public System.Nullable<double> TotalTime
		{
			get
			{
				return this._TotalTime;
			}
			set
			{
				if ((this._TotalTime != value))
				{
					this.OnTotalTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalTime = value;
					this.SendPropertyChanged("TotalTime");
					this.OnTotalTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Added", DbType="DateTime")]
		public System.Nullable<System.DateTime> Added
		{
			get
			{
				return this._Added;
			}
			set
			{
				if ((this._Added != value))
				{
					this.OnAddedChanging(value);
					this.SendPropertyChanging();
					this._Added = value;
					this.SendPropertyChanged("Added");
					this.OnAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROG", DbType="Int")]
		public System.Nullable<int> PROG
		{
			get
			{
				return this._PROG;
			}
			set
			{
				if ((this._PROG != value))
				{
					this.OnPROGChanging(value);
					this.SendPropertyChanging();
					this._PROG = value;
					this.SendPropertyChanged("PROG");
					this.OnPROGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signals", DbType="Int")]
		public System.Nullable<int> Signals
		{
			get
			{
				return this._Signals;
			}
			set
			{
				if ((this._Signals != value))
				{
					this.OnSignalsChanging(value);
					this.SendPropertyChanging();
					this._Signals = value;
					this.SendPropertyChanged("Signals");
					this.OnSignalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Float")]
		public System.Nullable<double> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TwkBitFlipCt", DbType="Int")]
		public System.Nullable<int> TwkBitFlipCt
		{
			get
			{
				return this._TwkBitFlipCt;
			}
			set
			{
				if ((this._TwkBitFlipCt != value))
				{
					this.OnTwkBitFlipCtChanging(value);
					this.SendPropertyChanging();
					this._TwkBitFlipCt = value;
					this.SendPropertyChanged("TwkBitFlipCt");
					this.OnTwkBitFlipCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unTestedScore", DbType="Float")]
		public System.Nullable<double> unTestedScore
		{
			get
			{
				return this._unTestedScore;
			}
			set
			{
				if ((this._unTestedScore != value))
				{
					this.OnunTestedScoreChanging(value);
					this.SendPropertyChanging();
					this._unTestedScore = value;
					this.SendPropertyChanged("unTestedScore");
					this.OnunTestedScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_midEntryPointScore", DbType="Float")]
		public System.Nullable<double> midEntryPointScore
		{
			get
			{
				return this._midEntryPointScore;
			}
			set
			{
				if ((this._midEntryPointScore != value))
				{
					this.OnmidEntryPointScoreChanging(value);
					this.SendPropertyChanging();
					this._midEntryPointScore = value;
					this.SendPropertyChanged("midEntryPointScore");
					this.OnmidEntryPointScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayScore", DbType="Float")]
		public System.Nullable<double> DisplayScore
		{
			get
			{
				return this._DisplayScore;
			}
			set
			{
				if ((this._DisplayScore != value))
				{
					this.OnDisplayScoreChanging(value);
					this.SendPropertyChanging();
					this._DisplayScore = value;
					this.SendPropertyChanged("DisplayScore");
					this.OnDisplayScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayUnTestedScore", DbType="Float")]
		public System.Nullable<double> DisplayUnTestedScore
		{
			get
			{
				return this._DisplayUnTestedScore;
			}
			set
			{
				if ((this._DisplayUnTestedScore != value))
				{
					this.OnDisplayUnTestedScoreChanging(value);
					this.SendPropertyChanging();
					this._DisplayUnTestedScore = value;
					this.SendPropertyChanged("DisplayUnTestedScore");
					this.OnDisplayUnTestedScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunCt", DbType="Int")]
		public System.Nullable<int> RunCt
		{
			get
			{
				return this._RunCt;
			}
			set
			{
				if ((this._RunCt != value))
				{
					this.OnRunCtChanging(value);
					this.SendPropertyChanging();
					this._RunCt = value;
					this.SendPropertyChanged("RunCt");
					this.OnRunCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinCt", DbType="Int")]
		public System.Nullable<int> WinCt
		{
			get
			{
				return this._WinCt;
			}
			set
			{
				if ((this._WinCt != value))
				{
					this.OnWinCtChanging(value);
					this.SendPropertyChanging();
					this._WinCt = value;
					this.SendPropertyChanged("WinCt");
					this.OnWinCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedReRunCt", DbType="Int")]
		public System.Nullable<int> FailedReRunCt
		{
			get
			{
				return this._FailedReRunCt;
			}
			set
			{
				if ((this._FailedReRunCt != value))
				{
					this.OnFailedReRunCtChanging(value);
					this.SendPropertyChanging();
					this._FailedReRunCt = value;
					this.SendPropertyChanged("FailedReRunCt");
					this.OnFailedReRunCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CutOffCt", DbType="Int")]
		public System.Nullable<int> CutOffCt
		{
			get
			{
				return this._CutOffCt;
			}
			set
			{
				if ((this._CutOffCt != value))
				{
					this.OnCutOffCtChanging(value);
					this.SendPropertyChanging();
					this._CutOffCt = value;
					this.SendPropertyChanged("CutOffCt");
					this.OnCutOffCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoChangeDetCt", DbType="Int")]
		public System.Nullable<int> NoChangeDetCt
		{
			get
			{
				return this._NoChangeDetCt;
			}
			set
			{
				if ((this._NoChangeDetCt != value))
				{
					this.OnNoChangeDetCtChanging(value);
					this.SendPropertyChanging();
					this._NoChangeDetCt = value;
					this.SendPropertyChanged("NoChangeDetCt");
					this.OnNoChangeDetCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegradeFloorCt", DbType="Int")]
		public System.Nullable<int> DegradeFloorCt
		{
			get
			{
				return this._DegradeFloorCt;
			}
			set
			{
				if ((this._DegradeFloorCt != value))
				{
					this.OnDegradeFloorCtChanging(value);
					this.SendPropertyChanging();
					this._DegradeFloorCt = value;
					this.SendPropertyChanged("DegradeFloorCt");
					this.OnDegradeFloorCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeepWithSmallDegCt", DbType="Int")]
		public System.Nullable<int> KeepWithSmallDegCt
		{
			get
			{
				return this._KeepWithSmallDegCt;
			}
			set
			{
				if ((this._KeepWithSmallDegCt != value))
				{
					this.OnKeepWithSmallDegCtChanging(value);
					this.SendPropertyChanging();
					this._KeepWithSmallDegCt = value;
					this.SendPropertyChanged("KeepWithSmallDegCt");
					this.OnKeepWithSmallDegCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedMinTrdCtRuleCt", DbType="Int")]
		public System.Nullable<int> FailedMinTrdCtRuleCt
		{
			get
			{
				return this._FailedMinTrdCtRuleCt;
			}
			set
			{
				if ((this._FailedMinTrdCtRuleCt != value))
				{
					this.OnFailedMinTrdCtRuleCtChanging(value);
					this.SendPropertyChanging();
					this._FailedMinTrdCtRuleCt = value;
					this.SendPropertyChanged("FailedMinTrdCtRuleCt");
					this.OnFailedMinTrdCtRuleCtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs0", DbType="Int")]
		public System.Nullable<int> Cutoffs0
		{
			get
			{
				return this._Cutoffs0;
			}
			set
			{
				if ((this._Cutoffs0 != value))
				{
					this.OnCutoffs0Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs0 = value;
					this.SendPropertyChanged("Cutoffs0");
					this.OnCutoffs0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs1", DbType="Int")]
		public System.Nullable<int> Cutoffs1
		{
			get
			{
				return this._Cutoffs1;
			}
			set
			{
				if ((this._Cutoffs1 != value))
				{
					this.OnCutoffs1Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs1 = value;
					this.SendPropertyChanged("Cutoffs1");
					this.OnCutoffs1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs2", DbType="Int")]
		public System.Nullable<int> Cutoffs2
		{
			get
			{
				return this._Cutoffs2;
			}
			set
			{
				if ((this._Cutoffs2 != value))
				{
					this.OnCutoffs2Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs2 = value;
					this.SendPropertyChanged("Cutoffs2");
					this.OnCutoffs2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs3", DbType="Int")]
		public System.Nullable<int> Cutoffs3
		{
			get
			{
				return this._Cutoffs3;
			}
			set
			{
				if ((this._Cutoffs3 != value))
				{
					this.OnCutoffs3Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs3 = value;
					this.SendPropertyChanged("Cutoffs3");
					this.OnCutoffs3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs4", DbType="Int")]
		public System.Nullable<int> Cutoffs4
		{
			get
			{
				return this._Cutoffs4;
			}
			set
			{
				if ((this._Cutoffs4 != value))
				{
					this.OnCutoffs4Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs4 = value;
					this.SendPropertyChanged("Cutoffs4");
					this.OnCutoffs4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs5", DbType="Int")]
		public System.Nullable<int> Cutoffs5
		{
			get
			{
				return this._Cutoffs5;
			}
			set
			{
				if ((this._Cutoffs5 != value))
				{
					this.OnCutoffs5Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs5 = value;
					this.SendPropertyChanged("Cutoffs5");
					this.OnCutoffs5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs6", DbType="Int")]
		public System.Nullable<int> Cutoffs6
		{
			get
			{
				return this._Cutoffs6;
			}
			set
			{
				if ((this._Cutoffs6 != value))
				{
					this.OnCutoffs6Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs6 = value;
					this.SendPropertyChanged("Cutoffs6");
					this.OnCutoffs6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs7", DbType="Int")]
		public System.Nullable<int> Cutoffs7
		{
			get
			{
				return this._Cutoffs7;
			}
			set
			{
				if ((this._Cutoffs7 != value))
				{
					this.OnCutoffs7Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs7 = value;
					this.SendPropertyChanged("Cutoffs7");
					this.OnCutoffs7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs8", DbType="Int")]
		public System.Nullable<int> Cutoffs8
		{
			get
			{
				return this._Cutoffs8;
			}
			set
			{
				if ((this._Cutoffs8 != value))
				{
					this.OnCutoffs8Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs8 = value;
					this.SendPropertyChanged("Cutoffs8");
					this.OnCutoffs8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs9", DbType="Int")]
		public System.Nullable<int> Cutoffs9
		{
			get
			{
				return this._Cutoffs9;
			}
			set
			{
				if ((this._Cutoffs9 != value))
				{
					this.OnCutoffs9Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs9 = value;
					this.SendPropertyChanged("Cutoffs9");
					this.OnCutoffs9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cutoffs10", DbType="Int")]
		public System.Nullable<int> Cutoffs10
		{
			get
			{
				return this._Cutoffs10;
			}
			set
			{
				if ((this._Cutoffs10 != value))
				{
					this.OnCutoffs10Changing(value);
					this.SendPropertyChanging();
					this._Cutoffs10 = value;
					this.SendPropertyChanged("Cutoffs10");
					this.OnCutoffs10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrdCtAvg", DbType="Float")]
		public System.Nullable<double> TrdCtAvg
		{
			get
			{
				return this._TrdCtAvg;
			}
			set
			{
				if ((this._TrdCtAvg != value))
				{
					this.OnTrdCtAvgChanging(value);
					this.SendPropertyChanging();
					this._TrdCtAvg = value;
					this.SendPropertyChanged("TrdCtAvg");
					this.OnTrdCtAvgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd0Ct", DbType="Float")]
		public System.Nullable<double> Trd0Ct
		{
			get
			{
				return this._Trd0Ct;
			}
			set
			{
				if ((this._Trd0Ct != value))
				{
					this.OnTrd0CtChanging(value);
					this.SendPropertyChanging();
					this._Trd0Ct = value;
					this.SendPropertyChanged("Trd0Ct");
					this.OnTrd0CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd1Ct", DbType="Float")]
		public System.Nullable<double> Trd1Ct
		{
			get
			{
				return this._Trd1Ct;
			}
			set
			{
				if ((this._Trd1Ct != value))
				{
					this.OnTrd1CtChanging(value);
					this.SendPropertyChanging();
					this._Trd1Ct = value;
					this.SendPropertyChanged("Trd1Ct");
					this.OnTrd1CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd2Ct", DbType="Float")]
		public System.Nullable<double> Trd2Ct
		{
			get
			{
				return this._Trd2Ct;
			}
			set
			{
				if ((this._Trd2Ct != value))
				{
					this.OnTrd2CtChanging(value);
					this.SendPropertyChanging();
					this._Trd2Ct = value;
					this.SendPropertyChanged("Trd2Ct");
					this.OnTrd2CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd3Ct", DbType="Float")]
		public System.Nullable<double> Trd3Ct
		{
			get
			{
				return this._Trd3Ct;
			}
			set
			{
				if ((this._Trd3Ct != value))
				{
					this.OnTrd3CtChanging(value);
					this.SendPropertyChanging();
					this._Trd3Ct = value;
					this.SendPropertyChanged("Trd3Ct");
					this.OnTrd3CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd4Ct", DbType="Float")]
		public System.Nullable<double> Trd4Ct
		{
			get
			{
				return this._Trd4Ct;
			}
			set
			{
				if ((this._Trd4Ct != value))
				{
					this.OnTrd4CtChanging(value);
					this.SendPropertyChanging();
					this._Trd4Ct = value;
					this.SendPropertyChanged("Trd4Ct");
					this.OnTrd4CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd5Ct", DbType="Float")]
		public System.Nullable<double> Trd5Ct
		{
			get
			{
				return this._Trd5Ct;
			}
			set
			{
				if ((this._Trd5Ct != value))
				{
					this.OnTrd5CtChanging(value);
					this.SendPropertyChanging();
					this._Trd5Ct = value;
					this.SendPropertyChanged("Trd5Ct");
					this.OnTrd5CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd6Ct", DbType="Float")]
		public System.Nullable<double> Trd6Ct
		{
			get
			{
				return this._Trd6Ct;
			}
			set
			{
				if ((this._Trd6Ct != value))
				{
					this.OnTrd6CtChanging(value);
					this.SendPropertyChanging();
					this._Trd6Ct = value;
					this.SendPropertyChanged("Trd6Ct");
					this.OnTrd6CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trd7Ct", DbType="Float")]
		public System.Nullable<double> Trd7Ct
		{
			get
			{
				return this._Trd7Ct;
			}
			set
			{
				if ((this._Trd7Ct != value))
				{
					this.OnTrd7CtChanging(value);
					this.SendPropertyChanging();
					this._Trd7Ct = value;
					this.SendPropertyChanged("Trd7Ct");
					this.OnTrd7CtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore0", DbType="Float")]
		public System.Nullable<double> MyScore0
		{
			get
			{
				return this._MyScore0;
			}
			set
			{
				if ((this._MyScore0 != value))
				{
					this.OnMyScore0Changing(value);
					this.SendPropertyChanging();
					this._MyScore0 = value;
					this.SendPropertyChanged("MyScore0");
					this.OnMyScore0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore1", DbType="Float")]
		public System.Nullable<double> MyScore1
		{
			get
			{
				return this._MyScore1;
			}
			set
			{
				if ((this._MyScore1 != value))
				{
					this.OnMyScore1Changing(value);
					this.SendPropertyChanging();
					this._MyScore1 = value;
					this.SendPropertyChanged("MyScore1");
					this.OnMyScore1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore2", DbType="Float")]
		public System.Nullable<double> MyScore2
		{
			get
			{
				return this._MyScore2;
			}
			set
			{
				if ((this._MyScore2 != value))
				{
					this.OnMyScore2Changing(value);
					this.SendPropertyChanging();
					this._MyScore2 = value;
					this.SendPropertyChanged("MyScore2");
					this.OnMyScore2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore3", DbType="Float")]
		public System.Nullable<double> MyScore3
		{
			get
			{
				return this._MyScore3;
			}
			set
			{
				if ((this._MyScore3 != value))
				{
					this.OnMyScore3Changing(value);
					this.SendPropertyChanging();
					this._MyScore3 = value;
					this.SendPropertyChanged("MyScore3");
					this.OnMyScore3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore4", DbType="Float")]
		public System.Nullable<double> MyScore4
		{
			get
			{
				return this._MyScore4;
			}
			set
			{
				if ((this._MyScore4 != value))
				{
					this.OnMyScore4Changing(value);
					this.SendPropertyChanging();
					this._MyScore4 = value;
					this.SendPropertyChanged("MyScore4");
					this.OnMyScore4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore5", DbType="Float")]
		public System.Nullable<double> MyScore5
		{
			get
			{
				return this._MyScore5;
			}
			set
			{
				if ((this._MyScore5 != value))
				{
					this.OnMyScore5Changing(value);
					this.SendPropertyChanging();
					this._MyScore5 = value;
					this.SendPropertyChanged("MyScore5");
					this.OnMyScore5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore6", DbType="Float")]
		public System.Nullable<double> MyScore6
		{
			get
			{
				return this._MyScore6;
			}
			set
			{
				if ((this._MyScore6 != value))
				{
					this.OnMyScore6Changing(value);
					this.SendPropertyChanging();
					this._MyScore6 = value;
					this.SendPropertyChanged("MyScore6");
					this.OnMyScore6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore7", DbType="Float")]
		public System.Nullable<double> MyScore7
		{
			get
			{
				return this._MyScore7;
			}
			set
			{
				if ((this._MyScore7 != value))
				{
					this.OnMyScore7Changing(value);
					this.SendPropertyChanging();
					this._MyScore7 = value;
					this.SendPropertyChanged("MyScore7");
					this.OnMyScore7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore8", DbType="Float")]
		public System.Nullable<double> MyScore8
		{
			get
			{
				return this._MyScore8;
			}
			set
			{
				if ((this._MyScore8 != value))
				{
					this.OnMyScore8Changing(value);
					this.SendPropertyChanging();
					this._MyScore8 = value;
					this.SendPropertyChanged("MyScore8");
					this.OnMyScore8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore9", DbType="Float")]
		public System.Nullable<double> MyScore9
		{
			get
			{
				return this._MyScore9;
			}
			set
			{
				if ((this._MyScore9 != value))
				{
					this.OnMyScore9Changing(value);
					this.SendPropertyChanging();
					this._MyScore9 = value;
					this.SendPropertyChanged("MyScore9");
					this.OnMyScore9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore10", DbType="Float")]
		public System.Nullable<double> MyScore10
		{
			get
			{
				return this._MyScore10;
			}
			set
			{
				if ((this._MyScore10 != value))
				{
					this.OnMyScore10Changing(value);
					this.SendPropertyChanging();
					this._MyScore10 = value;
					this.SendPropertyChanged("MyScore10");
					this.OnMyScore10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore11", DbType="Float")]
		public System.Nullable<double> MyScore11
		{
			get
			{
				return this._MyScore11;
			}
			set
			{
				if ((this._MyScore11 != value))
				{
					this.OnMyScore11Changing(value);
					this.SendPropertyChanging();
					this._MyScore11 = value;
					this.SendPropertyChanged("MyScore11");
					this.OnMyScore11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore12", DbType="Float")]
		public System.Nullable<double> MyScore12
		{
			get
			{
				return this._MyScore12;
			}
			set
			{
				if ((this._MyScore12 != value))
				{
					this.OnMyScore12Changing(value);
					this.SendPropertyChanging();
					this._MyScore12 = value;
					this.SendPropertyChanged("MyScore12");
					this.OnMyScore12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore13", DbType="Float")]
		public System.Nullable<double> MyScore13
		{
			get
			{
				return this._MyScore13;
			}
			set
			{
				if ((this._MyScore13 != value))
				{
					this.OnMyScore13Changing(value);
					this.SendPropertyChanging();
					this._MyScore13 = value;
					this.SendPropertyChanged("MyScore13");
					this.OnMyScore13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore14", DbType="Float")]
		public System.Nullable<double> MyScore14
		{
			get
			{
				return this._MyScore14;
			}
			set
			{
				if ((this._MyScore14 != value))
				{
					this.OnMyScore14Changing(value);
					this.SendPropertyChanging();
					this._MyScore14 = value;
					this.SendPropertyChanged("MyScore14");
					this.OnMyScore14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore15", DbType="Float")]
		public System.Nullable<double> MyScore15
		{
			get
			{
				return this._MyScore15;
			}
			set
			{
				if ((this._MyScore15 != value))
				{
					this.OnMyScore15Changing(value);
					this.SendPropertyChanging();
					this._MyScore15 = value;
					this.SendPropertyChanged("MyScore15");
					this.OnMyScore15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore16", DbType="Float")]
		public System.Nullable<double> MyScore16
		{
			get
			{
				return this._MyScore16;
			}
			set
			{
				if ((this._MyScore16 != value))
				{
					this.OnMyScore16Changing(value);
					this.SendPropertyChanging();
					this._MyScore16 = value;
					this.SendPropertyChanged("MyScore16");
					this.OnMyScore16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore17", DbType="Float")]
		public System.Nullable<double> MyScore17
		{
			get
			{
				return this._MyScore17;
			}
			set
			{
				if ((this._MyScore17 != value))
				{
					this.OnMyScore17Changing(value);
					this.SendPropertyChanging();
					this._MyScore17 = value;
					this.SendPropertyChanged("MyScore17");
					this.OnMyScore17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore18", DbType="Float")]
		public System.Nullable<double> MyScore18
		{
			get
			{
				return this._MyScore18;
			}
			set
			{
				if ((this._MyScore18 != value))
				{
					this.OnMyScore18Changing(value);
					this.SendPropertyChanging();
					this._MyScore18 = value;
					this.SendPropertyChanged("MyScore18");
					this.OnMyScore18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore19", DbType="Float")]
		public System.Nullable<double> MyScore19
		{
			get
			{
				return this._MyScore19;
			}
			set
			{
				if ((this._MyScore19 != value))
				{
					this.OnMyScore19Changing(value);
					this.SendPropertyChanging();
					this._MyScore19 = value;
					this.SendPropertyChanged("MyScore19");
					this.OnMyScore19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore20", DbType="Float")]
		public System.Nullable<double> MyScore20
		{
			get
			{
				return this._MyScore20;
			}
			set
			{
				if ((this._MyScore20 != value))
				{
					this.OnMyScore20Changing(value);
					this.SendPropertyChanging();
					this._MyScore20 = value;
					this.SendPropertyChanged("MyScore20");
					this.OnMyScore20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore21", DbType="Float")]
		public System.Nullable<double> MyScore21
		{
			get
			{
				return this._MyScore21;
			}
			set
			{
				if ((this._MyScore21 != value))
				{
					this.OnMyScore21Changing(value);
					this.SendPropertyChanging();
					this._MyScore21 = value;
					this.SendPropertyChanged("MyScore21");
					this.OnMyScore21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore22", DbType="Float")]
		public System.Nullable<double> MyScore22
		{
			get
			{
				return this._MyScore22;
			}
			set
			{
				if ((this._MyScore22 != value))
				{
					this.OnMyScore22Changing(value);
					this.SendPropertyChanging();
					this._MyScore22 = value;
					this.SendPropertyChanged("MyScore22");
					this.OnMyScore22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore23", DbType="Float")]
		public System.Nullable<double> MyScore23
		{
			get
			{
				return this._MyScore23;
			}
			set
			{
				if ((this._MyScore23 != value))
				{
					this.OnMyScore23Changing(value);
					this.SendPropertyChanging();
					this._MyScore23 = value;
					this.SendPropertyChanged("MyScore23");
					this.OnMyScore23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore24", DbType="Float")]
		public System.Nullable<double> MyScore24
		{
			get
			{
				return this._MyScore24;
			}
			set
			{
				if ((this._MyScore24 != value))
				{
					this.OnMyScore24Changing(value);
					this.SendPropertyChanging();
					this._MyScore24 = value;
					this.SendPropertyChanged("MyScore24");
					this.OnMyScore24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore25", DbType="Float")]
		public System.Nullable<double> MyScore25
		{
			get
			{
				return this._MyScore25;
			}
			set
			{
				if ((this._MyScore25 != value))
				{
					this.OnMyScore25Changing(value);
					this.SendPropertyChanging();
					this._MyScore25 = value;
					this.SendPropertyChanged("MyScore25");
					this.OnMyScore25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore26", DbType="Float")]
		public System.Nullable<double> MyScore26
		{
			get
			{
				return this._MyScore26;
			}
			set
			{
				if ((this._MyScore26 != value))
				{
					this.OnMyScore26Changing(value);
					this.SendPropertyChanging();
					this._MyScore26 = value;
					this.SendPropertyChanged("MyScore26");
					this.OnMyScore26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore27", DbType="Float")]
		public System.Nullable<double> MyScore27
		{
			get
			{
				return this._MyScore27;
			}
			set
			{
				if ((this._MyScore27 != value))
				{
					this.OnMyScore27Changing(value);
					this.SendPropertyChanging();
					this._MyScore27 = value;
					this.SendPropertyChanged("MyScore27");
					this.OnMyScore27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore28", DbType="Float")]
		public System.Nullable<double> MyScore28
		{
			get
			{
				return this._MyScore28;
			}
			set
			{
				if ((this._MyScore28 != value))
				{
					this.OnMyScore28Changing(value);
					this.SendPropertyChanging();
					this._MyScore28 = value;
					this.SendPropertyChanged("MyScore28");
					this.OnMyScore28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore29", DbType="Float")]
		public System.Nullable<double> MyScore29
		{
			get
			{
				return this._MyScore29;
			}
			set
			{
				if ((this._MyScore29 != value))
				{
					this.OnMyScore29Changing(value);
					this.SendPropertyChanging();
					this._MyScore29 = value;
					this.SendPropertyChanged("MyScore29");
					this.OnMyScore29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore30", DbType="Float")]
		public System.Nullable<double> MyScore30
		{
			get
			{
				return this._MyScore30;
			}
			set
			{
				if ((this._MyScore30 != value))
				{
					this.OnMyScore30Changing(value);
					this.SendPropertyChanging();
					this._MyScore30 = value;
					this.SendPropertyChanged("MyScore30");
					this.OnMyScore30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyScore31", DbType="Float")]
		public System.Nullable<double> MyScore31
		{
			get
			{
				return this._MyScore31;
			}
			set
			{
				if ((this._MyScore31 != value))
				{
					this.OnMyScore31Changing(value);
					this.SendPropertyChanging();
					this._MyScore31 = value;
					this.SendPropertyChanged("MyScore31");
					this.OnMyScore31Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
